%
% Copyright (c) 2021-present LAAS-CNRS
%
% SPDX-License-Identifier: GPL-2.0-or-later
%

classdef FakeScopeClient < handle
    properties
        Calls = {}
        FinalIndex = 17
    end

    methods
        function capture = download(obj, metadata, options)
            arguments
                obj
                metadata (1,1) struct
                options.Timeout = 15.0
            end
            obj.Calls{end+1} = struct( ...
                "metadata", metadata, "timeout", options.Timeout);
            capture = struct( ...
                "decimation", metadata.decimation, ...
                "samplePeriodUs", metadata.samplePeriodUs, ...
                "durationMs", metadata.durationMs, ...
                "channelNames", ScopeSerial.ChannelNames, ...
                "samples", zeros( ...
                    ScopeSerial.SampleCount, ...
                    numel(ScopeSerial.ChannelNames)), ...
                "finalIndex", obj.FinalIndex, ...
                "pretriggerRatio", metadata.pretriggerRatio, ...
                "timeAxisS", (0:(ScopeSerial.SampleCount - 1)).' * ...
                    metadata.samplePeriodUs * 1e-6);
        end
    end
end
