%
% Copyright (c) 2021-present LAAS-CNRS
%
% SPDX-License-Identifier: GPL-2.0-or-later
%

classdef test_ThingSetTools < matlab.unittest.TestCase
    methods (Test)
        function knownUnprefixedConfigItemsAreWritable(testCase)
            testCase.verifyEqual( ...
                ThingSetTools.classifyLeaf("Mode", "Config/Mode"), ...
                "writable");
            testCase.verifyEqual( ...
                ThingSetTools.classifyLeaf( ...
                    "Frequency_Hz", "/Config/Frequency_Hz"), ...
                "writable");
        end

        function prefixConventionIsPreserved(testCase)
            testCase.verifyEqual( ...
                ThingSetTools.classifyLeaf( ...
                    "wBoardName", "Converter/wBoardName"), ...
                "writable");
            testCase.verifyEqual( ...
                ThingSetTools.classifyLeaf( ...
                    "rV1Low_V", "Measurements/rV1Low_V"), ...
                "read-only");
            testCase.verifyEqual( ...
                ThingSetTools.classifyLeaf("cType", "Device/cType"), ...
                "informational");
        end
    end
end
